### ISSUE TITLE
Let the user populate the store before rendering (on server)

### ISSUE THREAD

**Issue by johangirod** [Evaneos/vitaminjs#11]
We need to allow the user to populate the store before rendering on server side. 
The most straightforward way, as I see it, would be to have the possibility to add a module `actionDispatcher` on the server config.

This module would export a function of the type : 
```
actionDispatcher : KoaRequest -> Dispatch -> Promise | void
```
- The `KoaRequest` being the [request object](http://koajs.com/#request) passed as the first argument
- The dispatch function passed as the second argument

And the function should return either void, either a Promise, if there is some async fetch going on. In this case, we wait until the promise resolve before rendering.

**Comment by tlenclos** [comment]
Yes it is really better than https://github.com/Evaneos/vitaminjs/pull/10.

**Comment by johangirod** [comment]
However this would *not* be the endorsed solution for populating the store. In 90% of case, we think that it would be better to use [AsyncProps](https://github.com/ryanflorence/async-props), as vitaminJS supports it natively. That's the solution we choose here to populate our store, and it has the advantage to be universal.

The idea behind it is to let the component specify how to load the data it needs for rendering. All you need to do is specify a static method loadProps on the component : 
```js
static loadProps({ params, loadContext: { dispatch } }, cb)
```

And yes, we will definitely need doc for all that ;)
