### ISSUE TITLE
when publicPath has http in it, public is not served

### ISSUE THREAD

**Issue by christophehurpeau** [Evaneos/vitaminjs#141]
https://github.com/Evaneos/vitaminjs/blob/b268361f3126f3877137ecca92e9eceafa285df3/src/server/middlewares/staticAssetsServer.js#L8

**Comment by johangirod** [comment]
Yes, indeed.
We should serve assets independantly of the publicPath, and add an option in the config to disable it (`servePublic``true` by default, can be set to false if you want to improve your perf)
