### ISSUE TITLE
Make vitamin a dev-dependency

### ISSUE THREAD

**Issue by johangirod** [Evaneos/vitaminjs#16]
Right now, vitamin is installed as a direct dependency.
This allows us to require vitaminjs dependency in the server bundle generated (thanks to a trick during the [webpack build](https://github.com/Evaneos/vitaminjs/blob/master/config/build/webpack.config.server.js#L20)). However this is not really natural.

A clearer and more understandable approach would be to limit vitamin as a _dev-dependency_ of a project. It becomes clear that it's aim is just to _facilitate development_ and _automatise build_. 

This means that we would have to move all the server package used in server rendering as `peer-dependencies` of vitaminjs. This would leads to a lot of peer-dependencies to install. In order to reduce boilerplate, maybe add a vitamin init which would install the peer dependencies ?

What do you think ?

**Comment by christophehurpeau** [comment]
I propose to create two separate libraires, `vitamin` and `vitamin-dev`.
One is used in the application, the second is used to build / lint / ... and has all the dependencies you only use in dev
I have this system in one of my libraries (alp) and I think it works well

**Comment by johangirod** [comment]
Thanks for you input ! Can't seem to find `alp` among your public repository in github.
Anyway, it seems like a good idea. After giving it some thoughts, I like the spirit of this solution, and I don't see any caveat up front.

I guess we'll have to try it out to be sure !

**Comment by christophehurpeau** [comment]
https://github.com/alpjs/ (Too many repo, I created organizations ^^)

**Comment by christophehurpeau** [comment]
Did you had any other reflexions on the road to 2.0 ?

**Comment by johangirod** [comment]
So, we thought about it, and the photo is self-explanatory :trollface: 

![img_20170510_180807](https://cloud.githubusercontent.com/assets/1775934/25909000/19a7b6f4-35ac-11e7-8910-e9038dfb37d8.jpg)

It's pretty simple, but it is the best separation:
- `vitamin-cli` becomes `vitaminjs` (install vitamin). It has the logic for init and forward other commands to `vitaminjs-build`
- `vitaminjs-runtime` re-exports `withStyles` and contains the `src` folder
- `vitaminjs-build` install the different commands in the `.bin` folder (`vitamin-start` `vitamin-build` ...etc)

**Comment by johangirod** [comment]
After discussion, we think it would be stupid to add a BC break just for change, so `vitaminjs-cli` will stay `vitaminjs-cli` and we will remove the `vitaminjs` package.

**Comment by mdarse** [comment]
Package splitting was implemented & merged in #387.
