### ISSUE TITLE
webpack-hot-middleware requires EventSource interface

### ISSUE THREAD

**Issue by alepee** [Evaneos/vitaminjs#204]
When EventSource interface is not available, `webpack-hot-middleware` dispatch a warning asking to use a polyfill for it to work.

> webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools

As pointed by [caniuse.com](http://caniuse.com/#feat=eventsource) EventSource is not supported by MSIE and Edge (under consideration).

We could add this polyfill as a `peer-dependency` and "inject" it when available OR should we let them do it manually ?

**Comment by christophehurpeau** [comment]
@alepee you could create a PR in https://github.com/Financial-Times/polyfill-service/tree/master/polyfills to make it available with https://cdn.polyfill.io/v2/docs/features/
