### ISSUE TITLE
react-router-4

### ISSUE THREAD

**Issue by johangirod** [Evaneos/vitaminjs#226]
We should implement react-router-4, which is a major improvement over react-router v3.
However, as it is still in beta, and would cause a breaking in vitaminJS, we should wait for the official release.

**Comment by alepee** [comment]
## Inspirations
- https://github.com/gabrielbull/react-router-server

## StaticRouter
- https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/StaticRouter.md
