### ISSUE TITLE
Use the babel preset `react-app`

### ISSUE THREAD

**Issue by johangirod** [Evaneos/vitaminjs#234]
We could use the babel preset from `create-react-app`. It's pretty sure to be well updated, and should be perfect for our use. Yay ? Nay ? 

https://github.com/facebookincubator/create-react-app/tree/master/packages/babel-preset-react-app

**Comment by christophehurpeau** [comment]
It doesn't work if we want to use all features of node 6.
The preset contains `babel-preset-latest` so and includes `babel-preset-es2015`

However, we should include in vitamin :
- babel-plugin-transform-react-jsx-source
- babel-plugin-transform-react-jsx-self

**Comment by christophehurpeau** [comment]
And also: `useBuiltIns: true`. There is a PR to make it work with presets: https://github.com/babel/babel/pull/5250

**Comment by johangirod** [comment]
That settles it, then !
