### ISSUE TITLE
redux-thunk

### ISSUE THREAD

**Issue by JiDai** [Evaneos/vitaminjs#260]
Hi,

How to use`redux-thunk` ? 
The documentation specify it is included by default but it does not work on my project. 
I just returned a `fetch` promise in my action and I got an error `Actions must be plain objects.`

**Comment by johangirod** [comment]
Hi 👋 

`redux-thunk` library enable dispatching of function, but not promises (you can refer to the doc here https://github.com/gaearon/redux-thunk#motivation). If you want to dispatch the result of a fetch, you can : 
- wrap it inside a call
```js 
const myActionCreator = (value) => (dispatch, getState) => {
    fetch(`https://myApi.com/values/${value}`)
        .then(result => dispatch({ type: MY_ACTION_TYPE, payload: result }))
};
```

- or add another middleware to redux. https://github.com/acdlite/redux-promise

**Comment by JiDai** [comment]
Obviously. I got confused :)
