### ISSUE TITLE
Integrate Saga with vitaminJS

### ISSUE THREAD

**Issue by vicdup** [Evaneos/vitaminjs#292]
Trying to use redux-saga with vitaminJS (thanks for the awesome work btw).

I understand how I can add the saga middleware to my store with the middleware key in vitaminrc. The issue is I need to then run the middleware sent to the store. No idea how to do that...

Here is the relevant part from the doc:

```javascript
import createSagaMiddleware from 'redux-saga'

// ...
import { helloSaga } from './sagas'

const sagaMiddleware = createSagaMiddleware()
const store = createStore(
  reducer,
  applyMiddleware(sagaMiddleware)
)
sagaMiddleware.run(helloSaga)
```

Any idea?

**Comment by johangirod** [comment]
It is possible to integrate Saga with vitaminJS. The trick is to export your sagaMiddleware, so that you can run it when your app initialize.

`middlewares.js`
```js
import createSagaMiddleware from 'redux-saga'

export const sagaMiddleware = createSagaMiddleware();
export default [ sagaMiddleware ];
``` 

`routes.js`
```js 
import { helloSaga } from './sagas';
import { sagaMiddleware } from './middlewares';

sagaMiddleware.run(helloSaga);
[...my routes.. ]
```


And there you go !

**Comment by vicdup** [comment]
Thanks for answering, that's what I thought but when I try that I still get 

```
Before running a Saga, you must mount the Saga middleware on the Store using applyMiddleware
```

**Comment by johangirod** [comment]
Oups, indeed, you need to make sure the store has been instanciated before running it. Hopefully, you can do that inside `routes.js`by exporting a function instead of your routes.

```js
import { helloSaga } from './sagas';
import { sagaMiddleware } from './middlewares';

const myRoutes = ...
export default () => {
    sagaMiddleware.run(helloSaga);
    return myRoutes;
};
```

The function is passed the store as a parameters, so you're sure that it has been created when it is called.

**Comment by vicdup** [comment]
Thanks for your reactivity, it seems to work expect I am now stuck with a  
```javascript
Uncaught ReferenceError: regeneratorRuntime is not defined
```

It seems that I am missing a pollyfill of some sort but the doc is not very clear on how I can add my own...
Can you help me again :-) ?

**Comment by alepee** [comment]
Hi @vicdup, it seems your not the only one who get this kind of trouble

according to [this post] you need to import [`babel-polyfill`](https://babeljs.io/docs/plugins/transform-regenerator/) prior to importing `redux-saga`

```js
import 'babel-polyfill';
import createSagaMiddleware from 'redux-saga'

export const sagaMiddleware = createSagaMiddleware();
export default [ sagaMiddleware ];
```

I did not tried it, but it seems to confort your thoughts

[this post]: http://mysticcoders.com/blog/fixing-regenerator-runtime-error-integrating-redux-saga

**Comment by johangirod** [comment]
Indeed, `redux-saga` uses generator, and generator recquire a runtime polyfill to work on the vast majority of browsers. We choose to not include it by default in `vitaminJS` because it adds some extra bytes to the build that most of the user won't use. But you can add it simply by importing it at the beginning of your routes. 

If you only need generators (and not core-js), you can just import `regenerator-runtime`
```js
import 'regenerator-runtime/runtime';
import createSagaMiddleware from 'redux-saga'

export const sagaMiddleware = createSagaMiddleware();
export default [ sagaMiddleware ];
 ```

We're going to update the FAQ, and add this section. Thanks for your input !

**Comment by vicdup** [comment]
Ahah thanks guys for all your help it's now working.

FYI it seems that it's more in the routes.js that you need the import

```javascript
import 'regenerator-runtime/runtime';
import { Route } from 'vitaminjs/react-router';
import Index from './Index';
import { helloSaga } from './Sagas';
import { sagaMiddleware } from './Middlewares';

const myRoutes = (
    <Route path="/" component={Index} />
);

export default () => {
    sagaMiddleware.run(helloSaga);
    return myRoutes;
};
```

Thanks again!

**Comment by vicdup** [comment]
@johangirod I don't want to open another issue for just a quick question, have you been able to run saga on server side ? For initial data for instance (we get some of our initial data through an API when the page is first loaded, I am wondering if it's possible to do it server side...).

**Comment by johangirod** [comment]
@vicdup, ok so I spent a little time thinking about this one, and the good news is that you can use redux-saga with vitaminJS for populating your store server-side.

One way to do it, would be to use the [createInitAction](https://github.com/Evaneos/vitaminjs/blob/master/API.md#createInitAction). 

> `createInitAction.js`
```es6
import myServerSideSaga from './serverSideSaga';
import sagaMiddleware from './sagaMiddleware';
...

export default (request) => (dispatch) => {
    const promise = sagaMiddleware.run(myServerSideSaga).done;
    dispatch({
        type: INIT_DATA,
        payload: serialize(request),
    });
    return promise;
}
```
In your saga, you will have different API calls depending on your incoming request. This would work, and it have the advantage to clearly separate your concerns, and be quite simple (see https://github.com/redux-saga/redux-saga/issues/13 for more infos);

---

The other solution is more elegant, but require a change in the vitaminJS API. We need to let the user hook after the rendering, something inspired by [the real world example on redux-saga](https://github.com/redux-saga/redux-saga/blob/master/examples/real-world/server.js). 

We should have it generic enough that any solution that enable the async rendering of component could be implemented thanks to it. It would be a necessary step on the road to a modular vitaminJS. 

I'm not sure what it should look like. I'm going to open an issue where we can discuss it.

**Comment by vicdup** [comment]
Hey @johangirod, thanks for answering ! I just saw your answer and I am trying it.

It seems to work correctly, I can see my action is dispatched (just put a console log in my reducer) and that my API call is made, I can see that my success action is triggered and the data are correct.

However this seems to block the page from loading in my browser, not sure what's happening here, not familiar enough with server side rendering unfortunately.

In case you have any idea on how to fix that, here is my createInitAction file...

Thanks again for your help,

```javascript
import indexSaga from './Sagas';
import { sagaMiddleware } from './Middlewares';
import SpotsActions from './Redux/SpotsRedux'

export default (request) => (dispatch) => {
    const promise = sagaMiddleware.run(indexSaga).done;
    dispatch(SpotsActions.request());
    return promise;
}
```
