### ISSUE TITLE
How to write custom Webpack loader

### ISSUE THREAD

**Issue by vicdup** [Evaneos/vitaminjs#304]
Hi All,

thanks again for the awesome work on this project.

Quick question I could not find the answer in the doc:
- How do you write your custom Webpack loader ? 

We're having trouble using icomoon with the current loaders. 

Thanks,
Victor

**Comment by johangirod** [comment]
Hello Victor, 
For now, you don't have the possibility to extends vitaminJS config. You can refer to #205 on the why we didn't ship with a plugin system. However, we are currently slowly evolving on this mentality and that's something we might consider for next major.
