### ISSUE TITLE
cURL error 52: Empty reply from server

### ISSUE THREAD

**Issue by AlexDpy** [Evaneos/vitaminjs#306]
Hello there!

We have an issue since we've switched to v1.0.0.
Randomly, the php service which does the curl call to vitamin server receives a curl error 52:
```
cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

We never had that error before v1.0.0.

It seems that this issue occurs since [this commit](https://github.com/Evaneos/vitaminjs/commit/30f502d71dbcbd8639e9793ba2c82f202dbb1a24)

This article might help to resolve this issue: http://joseoncode.com/2014/07/21/graceful-shutdown-in-node-dot-js/

**Comment by christophehurpeau** [comment]
https://www.npmjs.com/package/http-graceful-shutdown ?

**Comment by alepee** [comment]
when node `process` receives a `SIGINT`, `SIGTERM` or `SIGQUIT` signal, node `http.Server` must refuse any new incoming request and process already accepted ones before termination.
 
this should be fixed by https://github.com/Evaneos/vitaminjs/pull/313
