### ISSUE TITLE
Persist/rehydrate store

### ISSUE THREAD

**Issue by jazalizil** [Evaneos/vitaminjs#369]
I've added the autoRehydrate enhancer via the .vitaminrc config, and I call persistStore on client side in the constructor of my top-level component. The enhancer is called during the store initialization, but the persistance int the localstorage doesn't work.

.vitaminrc:
```
"redux": {
        "reducers": "./src/Redux",
        "middlewares": "./src/Middlewares",
        "enhancers": "./src/Enhancers"
}
```

Enhancers/index.js:
```
import { autoRehydrate } from 'redux-persist';

export default [autoRehydrate()];
```

routes index:
```
const myRoutes = {...}
export default (store) => {
  if (!!IS_CLIENT) persistStore(store, { blacklist: ['routing'], keyPrefix: 'myPrefix.' });
  sagaMiddleware.run(indexSaga);
  return myRoutes(store);
};```

**Comment by mdarse** [comment]
Hi,
From the information you provided, I'm not sure of the issue. By "persistance doesn't work", do you mean you get some error that pops out of Vitamin code or just that your local storage remain empty? Did you try to remove `redux-persist`'s `autoRehydrate` enhancer since that's an optional feature.

`redux-persist` is used internally with Vitamin at Evaneos without issue so it would be really helpful to have some the minimal reproducing code we can try on our side.

**Comment by jazalizil** [comment]
Well i mean the store is in my localstorage but the persistance doesn't work, it's always the initial states.
Does the problem coming from the hot reload? I tried to remove the enhancer, it doesn't work either.
I also moved the persistore call in the componentWillMount of my top level component. I realized that the state passed as the second argument of the callback fn contains the reducers of my app coming from the localstorage, but it doesn't rehydrate the store.
`persistore(store, {}, (old, THIS_STATE) => console.log('state rehydrated::', THIS_STATE))`

**Comment by jazalizil** [comment]
I figured out how to make it work. My problem was in src/shared/store.js line 10:
```
 const createStoreWithMiddleware = compose(
        applyMiddleware(...middlewares, thunk, routerMiddleware(history)),
        ...devEnhancers,
        ...appEnhancers,
    )(createStore);
```
I apply appEnhancer before devEnhancer, so autorehydrate is called before devenhancers like sattaman comments in this issue: https://github.com/rt2zz/redux-persist/issues/110#issuecomment-227769290
