### ISSUE TITLE
Make sure source maps are OK

### ISSUE THREAD

**Issue by mdarse** [Evaneos/vitaminjs#388]
- [x] Source maps are generated
- [x] Structure is OK per https://sourcemaps.io/
- [x] Line and **columns** are mapped on production source maps
- [x] Correct `sourceMappingURL` in generated JavaScript bundle
- [x] Original sources are inlined in source maps

**Comment by LucasPerso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [*](https://trello.com/c/xVPirdm9/12-untitled)

**Comment by LucasPerso** [comment]
Closed by #409
