### ISSUE TITLE
Self-transpilation of build toolchain at runtime

### ISSUE THREAD

**Issue by mdarse** [Evaneos/vitaminjs#390]
We should stop having the *build toolchain code* "self-transpiling" at runtime, and deprecate the usage of `babel-register`. Transpilation should be made upfront to clearly separate build and run stages.

**Comment by alepee** [comment]
Solved with:
https://github.com/Evaneos/vitaminjs/pull/411
https://github.com/Evaneos/vitaminjs/pull/412
