### ISSUE TITLE
Move vitamin executable in facade package

### ISSUE THREAD

**Issue by mdarse** [Evaneos/vitaminjs#396]
[makes sense only after #387 is merged]

Main `vitamin` command should live in `vitaminjs` package (preparing us for #395).
Only build related commands should live in `vitaminjs-build` package. To make command delegation easier for `vitamin` executable, `vitamin build --some-arg` will delegate his job to `vitamin-build --some-arg`:

Expected final state:
- `vitaminjs`
    - `bin/vitamin`
    - `bin/vitamin-new`
- `vitaminjs-build`
    - `bin/vitamin-build`
    - `bin/vitamin-clean`
    - `bin/vitamin-start`
- `vitaminjs-runtime`
    - `bin/vitamin-serve`

**Comment by LucasPerso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move vitamin executable in facade package](https://trello.com/c/MF8HKVNC/5-move-vitamin-executable-in-facade-package)
