### ISSUE TITLE
Vitamin displays incorrect HOST/PORT

### ISSUE THREAD

**Issue by oceyral** [Evaneos/vitaminjs#401]
When using vitamin to serve on interfaces other than the default `localhost`, vitamin always indicates that it is listening on `localhost:3000`, when it is not.

Exemple: 
```
HOST="0.0.0.0" PORT=9001 ./node_modules/.bin/vitamin serve
[ ... ]
✓ Server listening on: http://localhost:3000/xxx
```
Expected behavior : 
```
✓ Server listening on: http://0.0.0.0:9001/xxx
```

**Comment by alepee** [comment]
Thanks @oceyral, we will take a look at it.

**Comment by LucasPerso** [comment]
After inspection, the generated bundle is correctly using the env variables, but the print being already computed is not changed dynamically. This needs to be fixed.priority. It seems this bug is essentially aesthetics.

**Comment by LucasPerso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review PR Jest](https://trello.com/c/LL7lDCKN/14-review-pr-jest)
