### ISSUE TITLE
Cannot access koa app to set secret key to sign cookies

### ISSUE THREAD

**Issue by LucasPerso** [Evaneos/vitaminjs#416]
In some case, we would like to create a cookie on the server. This is easy thanks to Koa API however, if we want to sign the cookie, a secret key needs to be set as described here : http://koajs.com/#application

However in vitaminjs, the koa app is not exposed making it impossible to set a key, thus impossible to sign cookies.

I suggest that we open the possibility to do so through environment variables.

**Comment by mdarse** [comment]
I'm not sure I fully understand your use case, but you can access the `Application` instance through the [`app` property](http://koajs.com/#ctx-app) of the context passed to your middleware.

Don't hesitate to reopen this issue and give more details if I missed the point!
