### ISSUE TITLE
Handle dynamic require with webpack

### ISSUE THREAD

**Issue by LucasPerso** [Evaneos/vitaminjs#56]
Everything is in the title

**Comment by christophehurpeau** [comment]
I don't understand this issue

**Comment by johangirod** [comment]
Dynamic require with variable path are not supported by vitaminjs (https://webpack.github.io/docs/context.html). One use case for them are : I want to include only the traductions corresponding to the current locale. I can do something like 
```
require(`./traductions/${locale}`);
```

This doesn't work with vitaminjs.

**Comment by christophehurpeau** [comment]
Ah ok !

You mean:

```
System.import(`./traductions/${locale}`);
```
😄

**Comment by johangirod** [comment]
Well yes, you can use that too, but sometimes, you might want your
dependency to be bundled with the app...

**Comment by christophehurpeau** [comment]
related: https://github.com/Evaneos/vitaminjs/pull/145
